"""adding the machine_id foriegn key back to calls table

Revision ID: 7abf1db2d5f5
Revises: 5732df494fd6
Create Date: 2023-06-27 20:56:18.181294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abf1db2d5f5'
down_revision = '5732df494fd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('machine_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'calls', 'machines', ['machine_id'], ['machine_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.drop_column('calls', 'machine_id')
    # ### end Alembic commands ###
