"""adding cause and closed columns to calls table

Revision ID: bde318007570
Revises: 7abf1db2d5f5
Create Date: 2023-06-30 15:05:22.718941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde318007570'
down_revision = '7abf1db2d5f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('cause', sa.String(), nullable=True))
    op.add_column('calls', sa.Column('closed', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'closed')
    op.drop_column('calls', 'cause')
    # ### end Alembic commands ###
