"""adding nullable = False and sever def. to cause in call table

Revision ID: dfcb45b635dd
Revises: bde318007570
Create Date: 2023-06-30 15:41:32.969158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfcb45b635dd'
down_revision = 'bde318007570'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'cause',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'cause',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
