"""adding engineer response to calls

Revision ID: eba2f6c47cb9
Revises: dfcb45b635dd
Create Date: 2023-07-05 12:54:16.572937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba2f6c47cb9'
down_revision = 'dfcb45b635dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('engineer_response', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'engineer_response')
    # ### end Alembic commands ###
